/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.pravega.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class
Sample extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1269839050321848973L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Sample\",\"namespace\":\"io.pravega.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"counter\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Sample> ENCODER =
      new BinaryMessageEncoder<Sample>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Sample> DECODER =
      new BinaryMessageDecoder<Sample>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Sample> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Sample> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Sample>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Sample to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Sample from a ByteBuffer. */
  public static Sample fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public CharSequence id;
  @Deprecated public int counter;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Sample() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param counter The new value for counter
   */
  public Sample(CharSequence id, Integer counter) {
    this.id = id;
    this.counter = counter;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return counter;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: id = (CharSequence)value$; break;
    case 1: counter = (Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'counter' field.
   * @return The value of the 'counter' field.
   */
  public Integer getCounter() {
    return counter;
  }

  /**
   * Sets the value of the 'counter' field.
   * @param value the value to set.
   */
  public void setCounter(Integer value) {
    this.counter = value;
  }

  /**
   * Creates a new Sample RecordBuilder.
   * @return A new Sample RecordBuilder
   */
  public static io.pravega.avro.Sample.Builder newBuilder() {
    return new io.pravega.avro.Sample.Builder();
  }

  /**
   * Creates a new Sample RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Sample RecordBuilder
   */
  public static io.pravega.avro.Sample.Builder newBuilder(io.pravega.avro.Sample.Builder other) {
    return new io.pravega.avro.Sample.Builder(other);
  }

  /**
   * Creates a new Sample RecordBuilder by copying an existing Sample instance.
   * @param other The existing instance to copy.
   * @return A new Sample RecordBuilder
   */
  public static io.pravega.avro.Sample.Builder newBuilder(io.pravega.avro.Sample other) {
    return new io.pravega.avro.Sample.Builder(other);
  }

  /**
   * RecordBuilder for Sample instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Sample>
    implements org.apache.avro.data.RecordBuilder<Sample> {

    private CharSequence id;
    private int counter;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.pravega.avro.Sample.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.counter)) {
        this.counter = data().deepCopy(fields()[1].schema(), other.counter);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Sample instance
     * @param other The existing instance to copy.
     */
    private Builder(io.pravega.avro.Sample other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.counter)) {
        this.counter = data().deepCopy(fields()[1].schema(), other.counter);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.pravega.avro.Sample.Builder setId(CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.pravega.avro.Sample.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'counter' field.
      * @return The value.
      */
    public Integer getCounter() {
      return counter;
    }

    /**
      * Sets the value of the 'counter' field.
      * @param value The value of 'counter'.
      * @return This builder.
      */
    public io.pravega.avro.Sample.Builder setCounter(int value) {
      validate(fields()[1], value);
      this.counter = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'counter' field has been set.
      * @return True if the 'counter' field has been set, false otherwise.
      */
    public boolean hasCounter() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'counter' field.
      * @return This builder.
      */
    public io.pravega.avro.Sample.Builder clearCounter() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Sample build() {
      try {
        Sample record = new Sample();
        record.id = fieldSetFlags()[0] ? this.id : (CharSequence) defaultValue(fields()[0]);
        record.counter = fieldSetFlags()[1] ? this.counter : (Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Sample>
    WRITER$ = (org.apache.avro.io.DatumWriter<Sample>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Sample>
    READER$ = (org.apache.avro.io.DatumReader<Sample>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
